/** Minimum Phase 1 PR 1 ownership-issue reason codes. */

export const OWNERSHIP_REASON_CODES = [
  "INVALID_SHOP_DOMAIN",
  "CONFLICTING_NORMALIZED_DOMAIN",
  "EXISTING_SHOP_ID_MISMATCH",
  "MISSING_PARENT",
  "PARENT_SHOP_UNRESOLVED",
  "PARENT_CHILD_SHOP_MISMATCH",
  "PURCHASE_ORDER_SUPPLIER_SHOP_MISMATCH",
  "LEAD_TIME_PURCHASE_ORDER_MISSING",
  "LEAD_TIME_PURCHASE_ORDER_SHOP_MISMATCH",
  "DUPLICATE_SHOP_SETTINGS_TENANT",
] as const;

export type OwnershipReasonCode = (typeof OWNERSHIP_REASON_CODES)[number];
